name: Testing Artifacts
on:
  push:
    branches: [master]

env:
  IMAGE_TAG: "eb12f32"
  BUILD_BRANCH: "sprint"
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Creating File
        run: |
          mkdir artifacts
          echo $IMAGE_TAG > artifacts/${{env.BUILD_BRANCH}}-version

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_BRANCH}}-version
          path: artifacts/${{env.BUILD_BRANCH}}

  download:
    needs: [upload]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ${{env.BUILD_BRANCH}}-version
          path: artifacts/download
      - name: Save build version
        run: |
          cat "./artifacts/download/${{env.BUILD_BRANCH}}-version"
          echo "build=$(cat artifacts/download/${{env.BUILD_BRANCH}}-version)" >> $GITHUB_ENV

      - name: Validate version
        run: echo $build
