name: Testing cron
on:
  schedule:
    - cron: "*/15 * * * *"
    - cron: "*/30 * * * *"
jobs:
  test_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          if [ "${{ github.event.schedule }}" = "*/15 * * * *" ]; then
            echo "Minute"
          elif [ "${{ github.event.schedule }}" = "*/30* * * *" ]; then
            echo "2 Minute"
          else
            echo "Unknown schedule"
          fi
