name: Testing cron
on:
  schedule:
    - cron: "* * * * *"
    - cron: "*/2 * * * *"
jobs:
  test_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          if [ "${{ github.event.schedule }}" = "* * * * *" ]; then
            echo "Minute"
          elif [ "${{ github.event.schedule }}" = "*/2 * * * *" ]; then
            echo "2 Minute"
          else
            echo "Unknown schedule"
          fi
