name: Testing cron
on:
  push:
    branches: [master]

jobs:
  test_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Setting Env
        run: |
          echo "TEST=Test" >> $GITHUB_ENV
          echo "TEST_2=Test" >> $GITHUB_ENV
      - name: Viewing Env
        run: |
          echo $TEST
          echo ${{env.TEST_2}}
  test:
    uses: ./.github/workflows/test.yaml
    needs: [test_cron]
